export const SHOW_SPINNER = 'SHOW_SPINNER'
export const HIDE_SPINNER = 'HIDE_SPINNER'

export const TRANSACTIONS_GET_LIST = 'TRANSACTIONS_GET_LIST'
export const TRANSACTIONS_ADD = 'TRANSACTIONS_ADD'
export const TRANSACTIONS_EDIT = 'TRANSACTIONS_EDIT'
export const TRANSACTIONS_DELETE = 'TRANSACTIONS_DELETE'